name: halfmarathon
channels:
  - conda-forge
dependencies:
  - boto3
  - langfuse-python
  - matplotlib
  - numpy
  - openai
  - pandas
  - pycaret=3.3.2
  - python=3.11
  - python-dotenv
  - scikit-learn=1.4.*
  - seaborn
  - streamlit
  - pip:
    - colorlover==0.3.0

prefix: "/home/grzesiek/miniconda3/envs/halfmarathon"
